-- ============================================================================
-- Custody batches (feedstock_sourcing) rebuilt from the source workbook
--   "e. Work Process Data Collection.xlsx"
--
-- One row per distinct Batch ID found across the 7 stage sheets. CurrentStage is
-- the furthest stage that batch appears in. Generated, do not hand-edit; regen
-- from the workbook instead.
--
-- This replaces the DATA only. No table, column, index, policy or app code is
-- touched, so the Feedstock page and the Workflow > Custody tab keep working
-- exactly as they do now -- they both read this one table via useFeedstock().
--
-- Step 2 deletes every existing row. Run inside the transaction and check the
-- step 4 count before you commit.
-- ============================================================================

begin;

-- 1. What is there now.
select data->>'CurrentStage' as stage, count(*), min(data->>'Title') as sample_title
from feedstock_sourcing group by 1 order by 2 desc;

-- 2. Drop the seeded batches. Table and schema stay; only rows go.
delete from feedstock_sourcing;

-- 3. Insert the workbook batches.

insert into feedstock_sourcing (id, data) values ('fs_06072025-cyb', '{"Id": "fs_06072025-cyb", "Title": "06072025 CYB", "Type": "Woodchip", "Date": "2025-07-06", "Amount": "89.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 89.5, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_07052025-cyb', '{"Id": "fs_07052025-cyb", "Title": "07052025 CYB", "Type": "Woodchip", "Date": "2025-05-07", "Amount": "293", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 293.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_08012025-cyb', '{"Id": "fs_08012025-cyb", "Title": "08012025 CYB", "Type": "Woodchip", "Date": "2025-01-08", "Amount": "78", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 78.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_08092025-cyb', '{"Id": "fs_08092025-cyb", "Title": "08092025 CYB", "Type": "Woodchip", "Date": "2025-09-08", "Amount": "168", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 168.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_09012025-cyb', '{"Id": "fs_09012025-cyb", "Title": "09012025 CYB", "Type": "Woodchip", "Date": "2025-01-09", "Amount": "84.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 84.5, "PyrolysisTempC": 780.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_11082025-cyb', '{"Id": "fs_11082025-cyb", "Title": "11082025 CYB", "Type": "Woodchip", "Date": "2025-08-11", "Amount": "130", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 130.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_14102025-cyb', '{"Id": "fs_14102025-cyb", "Title": "14102025 CYB", "Type": "Woodchip", "Date": "2025-10-14", "Amount": "99", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 99.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_24042025-cyb', '{"Id": "fs_24042025-cyb", "Title": "24042025 CYB", "Type": "Woodchip", "Date": "2025-04-24", "Amount": "90", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 90.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_28042025-cyb', '{"Id": "fs_28042025-cyb", "Title": "28042025 CYB", "Type": "Woodchip", "Date": "2025-04-28", "Amount": "80", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 80.0, "PyrolysisTempC": 800.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_29042025-cyb', '{"Id": "fs_29042025-cyb", "Title": "29042025 CYB", "Type": "Woodchip", "Date": "2025-04-29", "Amount": "81", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 81.0, "PyrolysisTempC": 790.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_ecosfera-0-5-operation', '{"Id": "fs_ecosfera-0-5-operation", "Title": "Ecosfera 0.5 operation", "Type": "Woodchip", "Date": "", "Amount": "1664", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 1664.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_liquid-usage', '{"Id": "fs_liquid-usage", "Title": "Liquid Usage", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Application", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_oinc', '{"Id": "fs_oinc", "Title": "OINC", "Type": "Woodchip", "Date": "", "Amount": "100", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Application", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_production-on-2026', '{"Id": "fs_production-on-2026", "Title": "Production on 2026", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Material Conversion", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_qarbotech', '{"Id": "fs_qarbotech", "Title": "Qarbotech", "Type": "Woodchip", "Date": "", "Amount": "8900", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Application", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tggt', '{"Id": "fs_tggt", "Title": "TGGT-", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tggt-bt-2604-0001', '{"Id": "fs_tggt-bt-2604-0001", "Title": "TGGT-BT-2604-0001", "Type": "Woodchip", "Date": "2026-04-26", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2404-0001', '{"Id": "fs_tiggt-bt-2404-0001", "Title": "TIGGT-BT-2404-0001", "Type": "Woodchip", "Date": "2024-04-21", "Amount": "50", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2405-0001', '{"Id": "fs_tiggt-bt-2405-0001", "Title": "TIGGT-BT-2405-0001", "Type": "Woodchip", "Date": "2024-05-04", "Amount": "18.75", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2405-0002', '{"Id": "fs_tiggt-bt-2405-0002", "Title": "TIGGT-BT-2405-0002", "Type": "Woodchip", "Date": "2024-05-05", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2407-0001', '{"Id": "fs_tiggt-bt-2407-0001", "Title": "TIGGT-BT-2407-0001", "Type": "Woodchip", "Date": "2024-07-05", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2407-0002', '{"Id": "fs_tiggt-bt-2407-0002", "Title": "TIGGT-BT-2407-0002", "Type": "Woodchip", "Date": "2024-07-27", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2408-0002', '{"Id": "fs_tiggt-bt-2408-0002", "Title": "TIGGT-BT-2408-0002", "Type": "Woodchip", "Date": "2024-08-03", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2502-0001', '{"Id": "fs_tiggt-bt-2502-0001", "Title": "TIGGT-BT-2502-0001", "Type": "Woodchip", "Date": "2025-02-10", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2503-0001', '{"Id": "fs_tiggt-bt-2503-0001", "Title": "TIGGT-BT-2503-0001", "Type": "Woodchip", "Date": "2025-03-31", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2505-0001', '{"Id": "fs_tiggt-bt-2505-0001", "Title": "TIGGT-BT-2505-0001", "Type": "Woodchip", "Date": "2025-05-17", "Amount": "100", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2505-0002', '{"Id": "fs_tiggt-bt-2505-0002", "Title": "TIGGT-BT-2505-0002", "Type": "Woodchip", "Date": "2025-05-24", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2506-0001', '{"Id": "fs_tiggt-bt-2506-0001", "Title": "TIGGT-BT-2506-0001", "Type": "Woodchip", "Date": "2025-06-16", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2507-0001', '{"Id": "fs_tiggt-bt-2507-0001", "Title": "TIGGT-BT-2507-0001", "Type": "Woodchip", "Date": "2025-07-05", "Amount": "200", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2508-0001', '{"Id": "fs_tiggt-bt-2508-0001", "Title": "TIGGT-BT-2508-0001", "Type": "Woodchip", "Date": "2025-08-15", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2508-0002', '{"Id": "fs_tiggt-bt-2508-0002", "Title": "TIGGT-BT-2508-0002", "Type": "Woodchip", "Date": "2025-08-29", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2509-0001', '{"Id": "fs_tiggt-bt-2509-0001", "Title": "TIGGT-BT-2509-0001", "Type": "Woodchip", "Date": "2025-09-27", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2510-0001', '{"Id": "fs_tiggt-bt-2510-0001", "Title": "TIGGT-BT-2510-0001", "Type": "Woodchip", "Date": "2025-10-08", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2512-0001', '{"Id": "fs_tiggt-bt-2512-0001", "Title": "TIGGT-BT-2512-0001", "Type": "Woodchip", "Date": "2025-12-14", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2512-0002', '{"Id": "fs_tiggt-bt-2512-0002", "Title": "TIGGT-BT-2512-0002", "Type": "Woodchip", "Date": "2025-12-16", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2512-0003', '{"Id": "fs_tiggt-bt-2512-0003", "Title": "TIGGT-BT-2512-0003", "Type": "Woodchip", "Date": "2025-12-22", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2601-0002', '{"Id": "fs_tiggt-bt-2601-0002", "Title": "TIGGT-BT-2601-0002", "Type": "Woodchip", "Date": "2026-01-24", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_tiggt-bt-2602-0001', '{"Id": "fs_tiggt-bt-2602-0001", "Title": "TIGGT-BT-2602-0001", "Type": "Woodchip", "Date": "2026-02-05", "Amount": "", "Status": "Verified", "Supplier": "Tigasfera Greentech", "CurrentStage": "Carbon Sink", "IsWaste": false, "IsPending": false}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_week-2', '{"Id": "fs_week-2", "Title": "Week 2", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_week-3', '{"Id": "fs_week-3", "Title": "Week 3", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_week-4', '{"Id": "fs_week-4", "Title": "Week 4", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_week-5', '{"Id": "fs_week-5", "Title": "Week 5", "Type": "Woodchip", "Date": "", "Amount": "", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-01-25', '{"Id": "fs_za-01-01-25", "Title": "ZA-01-01-25", "Type": "Ash", "Date": "2025-01-02", "Amount": "39.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 39.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-01-26', '{"Id": "fs_za-01-01-26", "Title": "ZA-01-01-26", "Type": "Woodchip", "Date": "2026-01-05", "Amount": "210", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 210.0, "PyrolysisTempC": 410.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-02-25', '{"Id": "fs_za-01-02-25", "Title": "ZA-01-02-25", "Type": "Woodchip", "Date": "2025-02-03", "Amount": "49.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 49.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-02-26', '{"Id": "fs_za-01-02-26", "Title": "ZA-01-02-26", "Type": "Woodchip", "Date": "2026-02-05", "Amount": "207", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 207.0, "PyrolysisTempC": 410.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-03-25', '{"Id": "fs_za-01-03-25", "Title": "ZA-01-03-25", "Type": "Woodchip", "Date": "2025-03-03", "Amount": "67.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 67.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-04-25', '{"Id": "fs_za-01-04-25", "Title": "ZA-01-04-25", "Type": "Woodchip", "Date": "2025-04-07", "Amount": "72", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 72.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-05-25', '{"Id": "fs_za-01-05-25", "Title": "ZA-01-05-25", "Type": "Woodchip", "Date": "2025-05-02", "Amount": "7", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 7.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-06-25', '{"Id": "fs_za-01-06-25", "Title": "ZA-01-06-25", "Type": "Woodchip", "Date": "2025-06-03", "Amount": "226", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 226.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-07-25', '{"Id": "fs_za-01-07-25", "Title": "ZA-01-07-25", "Type": "Vertiver Grass", "Date": "2025-07-08", "Amount": "91.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 91.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-08-25', '{"Id": "fs_za-01-08-25", "Title": "ZA-01-08-25", "Type": "EFB", "Date": "2025-08-01", "Amount": "5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 5.0, "PyrolysisTempC": 380.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-09-25', '{"Id": "fs_za-01-09-25", "Title": "ZA-01-09-25", "Type": "Rice Husk", "Date": "2025-09-02", "Amount": "521", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 521.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-10-25', '{"Id": "fs_za-01-10-25", "Title": "ZA-01-10-25", "Type": "Woodchip", "Date": "2025-10-02", "Amount": "125", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 125.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-18', '{"Id": "fs_za-01-11-18", "Title": "ZA-01-11-18", "Type": "Woodchip", "Date": "2024-11-04", "Amount": "700", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-19', '{"Id": "fs_za-01-11-19", "Title": "ZA-01-11-19", "Type": "Woodchip", "Date": "2024-11-05", "Amount": "650", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-20', '{"Id": "fs_za-01-11-20", "Title": "ZA-01-11-20", "Type": "Woodchip", "Date": "2024-11-06", "Amount": "800", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-21', '{"Id": "fs_za-01-11-21", "Title": "ZA-01-11-21", "Type": "Woodchip", "Date": "2024-11-07", "Amount": "600", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-22', '{"Id": "fs_za-01-11-22", "Title": "ZA-01-11-22", "Type": "Woodchip", "Date": "2024-11-08", "Amount": "500", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-24', '{"Id": "fs_za-01-11-24", "Title": "ZA-01-11-24", "Type": "Woodchip", "Date": "2024-11-01", "Amount": "5000", "Status": "Pending", "Supplier": "Cyberjaya", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 82.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-11-25', '{"Id": "fs_za-01-11-25", "Title": "ZA-01-11-25", "Type": "Woodchip", "Date": "2025-01-06", "Amount": "1180", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 172.0, "PyrolysisTempC": 410.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-12-24', '{"Id": "fs_za-01-12-24", "Title": "ZA-01-12-24", "Type": "Ash", "Date": "2024-12-02", "Amount": "49", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 49.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-01-12-25', '{"Id": "fs_za-01-12-25", "Title": "ZA-01-12-25", "Type": "Woodchip", "Date": "2025-12-01", "Amount": "256", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 256.0, "PyrolysisTempC": 410.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-01-25', '{"Id": "fs_za-02-01-25", "Title": "ZA-02-01-25", "Type": "Ash", "Date": "2025-01-06", "Amount": "106", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 106.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-01-26', '{"Id": "fs_za-02-01-26", "Title": "ZA-02-01-26", "Type": "Woodchip", "Date": "2026-01-12", "Amount": "186", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 186.0, "PyrolysisTempC": 420.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-02-25', '{"Id": "fs_za-02-02-25", "Title": "ZA-02-02-25", "Type": "Woodchip", "Date": "2025-02-10", "Amount": "84", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 84.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-02-26', '{"Id": "fs_za-02-02-26", "Title": "ZA-02-02-26", "Type": "Woodchip", "Date": "2026-02-09", "Amount": "452", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 452.0, "PyrolysisTempC": 420.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-03-25', '{"Id": "fs_za-02-03-25", "Title": "ZA-02-03-25", "Type": "Woodchip", "Date": "2025-03-11", "Amount": "52", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 52.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-04-25', '{"Id": "fs_za-02-04-25", "Title": "ZA-02-04-25", "Type": "Woodchip", "Date": "2025-04-14", "Amount": "65", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 65.0, "PyrolysisTempC": 380.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-05-25', '{"Id": "fs_za-02-05-25", "Title": "ZA-02-05-25", "Type": "Woodchip", "Date": "2025-05-05", "Amount": "35.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 35.5, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-06-25', '{"Id": "fs_za-02-06-25", "Title": "ZA-02-06-25", "Type": "Woodchip", "Date": "2025-06-12", "Amount": "394", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 394.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-08-25', '{"Id": "fs_za-02-08-25", "Title": "ZA-02-08-25", "Type": "EFB", "Date": "2025-08-05", "Amount": "1490.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 1490.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-09-25', '{"Id": "fs_za-02-09-25", "Title": "ZA-02-09-25", "Type": "Woodchip", "Date": "2025-09-08", "Amount": "375", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 375.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-10-25', '{"Id": "fs_za-02-10-25", "Title": "ZA-02-10-25", "Type": "Woodchip", "Date": "2025-10-06", "Amount": "255", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 255.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-11-24', '{"Id": "fs_za-02-11-24", "Title": "ZA-02-11-24", "Type": "Woodchip", "Date": "2024-11-06", "Amount": "5000", "Status": "Pending", "Supplier": "Cyberjaya", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 67.5, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-11-25', '{"Id": "fs_za-02-11-25", "Title": "ZA-02-11-25", "Type": "Woodchip", "Date": "2025-02-10", "Amount": "3070", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 112.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-12-24', '{"Id": "fs_za-02-12-24", "Title": "ZA-02-12-24", "Type": "Ash", "Date": "2024-12-09", "Amount": "66", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 66.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-02-12-25', '{"Id": "fs_za-02-12-25", "Title": "ZA-02-12-25", "Type": "Woodchip", "Date": "2025-12-08", "Amount": "170", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 170.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-01-25', '{"Id": "fs_za-03-01-25", "Title": "ZA-03-01-25", "Type": "Ash", "Date": "2025-01-14", "Amount": "55.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 55.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-01-26', '{"Id": "fs_za-03-01-26", "Title": "ZA-03-01-26", "Type": "Woodchip", "Date": "2026-01-19", "Amount": "260", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 260.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-02-25', '{"Id": "fs_za-03-02-25", "Title": "ZA-03-02-25", "Type": "Woodchip", "Date": "2025-02-17", "Amount": "52.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 52.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-02-26', '{"Id": "fs_za-03-02-26", "Title": "ZA-03-02-26", "Type": "Woodchip", "Date": "2026-02-24", "Amount": "184", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 184.0, "PyrolysisTempC": 410.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-03-25', '{"Id": "fs_za-03-03-25", "Title": "ZA-03-03-25", "Type": "Woodchip", "Date": "2025-03-19", "Amount": "39.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 39.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-04-25', '{"Id": "fs_za-03-04-25", "Title": "ZA-03-04-25", "Type": "Woodchip", "Date": "2025-04-21", "Amount": "40.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 40.5, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-05-25', '{"Id": "fs_za-03-05-25", "Title": "ZA-03-05-25", "Type": "Woodchip", "Date": "2025-05-13", "Amount": "70", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 70.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-06-25', '{"Id": "fs_za-03-06-25", "Title": "ZA-03-06-25", "Type": "Bamboo", "Date": "2025-06-17", "Amount": "70", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 70.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-08-25', '{"Id": "fs_za-03-08-25", "Title": "ZA-03-08-25", "Type": "Sawmill", "Date": "2025-08-12", "Amount": "200", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 200.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-09-25', '{"Id": "fs_za-03-09-25", "Title": "ZA-03-09-25", "Type": "PKS", "Date": "2025-09-17", "Amount": "470", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 470.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-10-25', '{"Id": "fs_za-03-10-25", "Title": "ZA-03-10-25", "Type": "Woodchip", "Date": "2025-10-15", "Amount": "215", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 215.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-11-24', '{"Id": "fs_za-03-11-24", "Title": "ZA-03-11-24", "Type": "Woodchip", "Date": "2024-11-12", "Amount": "5000", "Status": "Pending", "Supplier": "Cyberjaya", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 57.5, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-11-25', '{"Id": "fs_za-03-11-25", "Title": "ZA-03-11-25", "Type": "Woodchip", "Date": "2025-05-13", "Amount": "4040", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 82.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-12-24', '{"Id": "fs_za-03-12-24", "Title": "ZA-03-12-24", "Type": "Ash", "Date": "2024-12-17", "Amount": "36.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 36.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-03-12-25', '{"Id": "fs_za-03-12-25", "Title": "ZA-03-12-25", "Type": "EFB", "Date": "2025-12-15", "Amount": "50", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 50.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-01-25', '{"Id": "fs_za-04-01-25", "Title": "ZA-04-01-25", "Type": "Woodchip", "Date": "2025-01-21", "Amount": "13", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 13.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-01-26', '{"Id": "fs_za-04-01-26", "Title": "ZA-04-01-26", "Type": "Woodchip", "Date": "2026-01-26", "Amount": "165", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 165.0, "PyrolysisTempC": 420.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-02-25', '{"Id": "fs_za-04-02-25", "Title": "ZA-04-02-25", "Type": "Woodchip", "Date": "2025-02-25", "Amount": "25", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 25.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-03-25', '{"Id": "fs_za-04-03-25", "Title": "ZA-04-03-25", "Type": "Woodchip", "Date": "2025-03-26", "Amount": "29", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 29.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-04-25', '{"Id": "fs_za-04-04-25", "Title": "ZA-04-04-25", "Type": "Woodchip", "Date": "2025-04-28", "Amount": "42", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 42.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-05-25', '{"Id": "fs_za-04-05-25", "Title": "ZA-04-05-25", "Type": "Woodchip", "Date": "2025-05-19", "Amount": "246.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 246.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-06-25', '{"Id": "fs_za-04-06-25", "Title": "ZA-04-06-25", "Type": "Bamboo", "Date": "2025-06-24", "Amount": "7.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 7.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-08-25', '{"Id": "fs_za-04-08-25", "Title": "ZA-04-08-25", "Type": "Rice Husk", "Date": "2025-08-18", "Amount": "153.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 153.5, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-09-25', '{"Id": "fs_za-04-09-25", "Title": "ZA-04-09-25", "Type": "Woodchip", "Date": "2025-09-23", "Amount": "150", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 150.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-10-25', '{"Id": "fs_za-04-10-25", "Title": "ZA-04-10-25", "Type": "Woodchip", "Date": "2025-10-21", "Amount": "70", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 70.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-11-24', '{"Id": "fs_za-04-11-24", "Title": "ZA-04-11-24", "Type": "Woodchip", "Date": "2024-11-21", "Amount": "5000", "Status": "Pending", "Supplier": "Cyberjaya", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 32.0, "PyrolysisTempC": 380.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-11-25', '{"Id": "fs_za-04-11-25", "Title": "ZA-04-11-25", "Type": "Woodchip", "Date": "2025-11-24", "Amount": "210", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 210.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-12-24', '{"Id": "fs_za-04-12-24", "Title": "ZA-04-12-24", "Type": "Ash", "Date": "2024-12-26", "Amount": "19", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 19.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-04-12-25', '{"Id": "fs_za-04-12-25", "Title": "ZA-04-12-25", "Type": "Woodchip", "Date": "2025-12-26", "Amount": "60", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 60.0, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-01-25', '{"Id": "fs_za-05-01-25", "Title": "ZA-05-01-25", "Type": "Woodchip", "Date": "2025-01-28", "Amount": "9", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 9.0, "PyrolysisTempC": 370.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-05-25', '{"Id": "fs_za-05-05-25", "Title": "ZA-05-05-25", "Type": "Woodchip", "Date": "2025-05-27", "Amount": "236.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 236.5, "PyrolysisTempC": 390.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-08-25', '{"Id": "fs_za-05-08-25", "Title": "ZA-05-08-25", "Type": "Rice Husk", "Date": "2025-08-27", "Amount": "177.5", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 177.5, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-09-25', '{"Id": "fs_za-05-09-25", "Title": "ZA-05-09-25", "Type": "Woodchip", "Date": "2025-09-30", "Amount": "150", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Storage", "IsWaste": false, "IsPending": true, "BiocharYieldKg": 150.0, "PyrolysisTempC": 400.0}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-11-24', '{"Id": "fs_za-05-11-24", "Title": "ZA-05-11-24", "Type": "Woodchip", "Date": "2024-11-27", "Amount": "5000", "Status": "Pending", "Supplier": "Cyberjaya", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-11-25', '{"Id": "fs_za-05-11-25", "Title": "ZA-05-11-25", "Type": "Woodchip", "Date": "2025-11-10", "Amount": "2400", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;
insert into feedstock_sourcing (id, data) values ('fs_za-05-11-26', '{"Id": "fs_za-05-11-26", "Title": "ZA-05-11-26", "Type": "Woodchip", "Date": "2026-01-05", "Amount": "680", "Status": "Pending", "Supplier": "Tigasfera Greentech", "CurrentStage": "Feedstock Pre-Processing", "IsWaste": false, "IsPending": true}'::jsonb) on conflict (id) do update set data = excluded.data;

-- 4. Sanity check: should return 114 rows.
select count(*) from feedstock_sourcing;

commit;
