-- ============================================================================
-- External biochar purchases, from the workbook's "External biochar" sheet.
--
-- Generated by scripts/gen-external-biochar.py — do not hand-edit; regenerate.
--
-- Bought-in biochar, not produced on site. Loaded as `warehouse` entries with
-- product "External Biochar" (that stage already carries exactly that option),
-- so no schema, stage or form changes are needed.
--
-- Volumes are normalized to kg. The sheet writes free text such as "3 Tonne";
-- the original wording is preserved in remarks so the conversion is auditable.
--
-- Batch ids are synthesized as EXT-<SOURCE>-<YYYYMMDD> because the sheet has no
-- id column. They identify a receipt that happened; they assert NO link to any
-- production batch or shipment.
--
-- ‼️  CARBON ACCOUNTING: this material was produced by a third party. It counts
--     as supply for physical mass balance, but must NOT be claimed as own
--     production for CORC issuance — whoever produced it has that claim.
--     massBalance.ts keeps the two separate; don't collapse them.
--
-- Safe to re-run: `on conflict (id) do nothing`.
-- ============================================================================

begin;

insert into work_process_entries (id, data) values ('wpe_warehouse_ext_0001', '{"Id": "wpe_warehouse_ext_0001", "StageKey": "warehouse", "StageTitle": "Warehouse", "Values": {"batch_id": "EXT-AU-SYNERGY-20240821", "date": "2024-08-21", "product": "External Biochar", "quantity": "3000", "storage_location": "Biochar Store", "remarks": "External purchase from AU Synergy \u00b7 Biochar (EFB) \u00b7 source sheet records \"3 Tonne\""}, "CapturedBy": "Imported (Excel \u2014 External biochar sheet)", "Timestamp": "2024-08-21T00:00:00Z"}'::jsonb) on conflict (id) do nothing;

-- Sanity check: 1 row(s), 3000 kg of external biochar.
select count(*) as external_rows,
       sum((data->'Values'->>'quantity')::numeric) as total_kg
from work_process_entries
where data->>'StageKey' = 'warehouse'
  and data->'Values'->>'product' = 'External Biochar';

commit;
