"""
Generate work-process entries for the workbook's "External biochar" sheet.

Biochar bought in rather than produced on site. The Dashboard counts it as
Receiving stock (3,000 kg) and draws 2,400 kg of it into Application, but no
importer read the sheet, so the app's inventory was short by that much.

Imported as `warehouse` entries with product "External Biochar" — that stage
already exists with exactly that product option and a kg Quantity field, so no
new stage or form is needed.

TWO THINGS THIS SCRIPT IS CAREFUL ABOUT
  1. Units. The sheet records volume as free text ("3 Tonne"). Stored raw, the
     amount parser reads the leading number and yields 3 kg instead of 3,000 —
     a 1000x undercount. Everything is normalized to kg here, with the original
     text preserved in remarks so the conversion stays auditable.
  2. Provenance. The batch id is synthesized (EXT-<SOURCE>-<YYYYMMDD>) because
     the sheet has no id column. That is an identifier for a receipt that
     demonstrably happened — it asserts no link to any production batch or
     shipment. Nothing here infers custody.

Regenerate rather than hand-editing the SQL:
    python scripts/gen-external-biochar.py
"""

import datetime
import json
import os
import re
import sys

import openpyxl

SRC = os.environ.get(
    "WORKBOOK",
    r"C:\Users\muhdi\Downloads\e. Work Process Data Collection. xlsx (1) (1).xlsx",
)
OUT = "security/seed-external-biochar.sql"
SHEET = "External biochar"

# Free-text volume -> kg. The sheet writes "3 Tonne"; operators may also write
# "500kg", "1.5 t", "2 MT". Anything without a recognized unit is assumed kg.
TO_KG = {
    "kg": 1.0, "kgs": 1.0, "kilogram": 1.0, "kilograms": 1.0,
    "t": 1000.0, "mt": 1000.0, "ton": 1000.0, "tons": 1000.0,
    "tonne": 1000.0, "tonnes": 1000.0,
}


def to_kg(raw):
    """(kg, original_text) or (None, original_text) when unparseable."""
    if raw is None:
        return None, ""
    text = str(raw).strip()
    if isinstance(raw, (int, float)):
        return float(raw), text  # bare number: sheet's own unit is kg
    m = re.match(r"\s*(-?\d*\.?\d+)\s*([A-Za-z]*)", text.replace(",", ""))
    if not m:
        return None, text
    value = float(m.group(1))
    unit = m.group(2).lower()
    if unit and unit not in TO_KG:
        return None, text  # unrecognized unit: refuse to guess
    return value * TO_KG.get(unit, 1.0), text


def as_date(v):
    if isinstance(v, (datetime.datetime, datetime.date)):
        return v.strftime("%Y-%m-%d")
    return None


def slug(s):
    return re.sub(r"[^A-Z0-9]+", "-", str(s).upper()).strip("-")


wb = openpyxl.load_workbook(SRC, data_only=True)
ws = wb[SHEET]

rows, skipped = [], []
for r in range(5, ws.max_row + 1):  # row 4 is the header
    date_cell, source, ctype, vol = (ws.cell(r, c).value for c in range(1, 5))
    date = as_date(date_cell)
    if not date or source is None:
        continue  # blank row or the trailing internal-use note
    kg, raw_vol = to_kg(vol)
    if kg is None:
        skipped.append((r, source, raw_vol))
        continue
    rows.append({
        "row": r,
        "date": date,
        "source": str(source).strip(),
        "type": str(ctype).strip() if ctype else "",
        "kg": kg,
        "raw_vol": raw_vol,
    })

if skipped:
    print("!! Unparseable volume — fix the sheet, these are NOT in the output:")
    for r, source, raw in skipped:
        print(f"   row {r}: {source!r} vol={raw!r}")

docs = []
for i, x in enumerate(rows, start=1):
    batch_id = f"EXT-{slug(x['source'])}-{x['date'].replace('-', '')}"
    remarks = f"External purchase from {x['source']}"
    if x["type"]:
        remarks += f" · {x['type']}"
    remarks += f" · source sheet records \"{x['raw_vol']}\""
    docs.append({
        "Id": f"wpe_warehouse_ext_{i:04d}",
        "StageKey": "warehouse",
        "StageTitle": "Warehouse",
        "Values": {
            "batch_id": batch_id,
            "date": x["date"],
            "product": "External Biochar",
            "quantity": f"{x['kg']:g}",
            "storage_location": "Biochar Store",
            "remarks": remarks,
        },
        "CapturedBy": "Imported (Excel — External biochar sheet)",
        "Timestamp": f"{x['date']}T00:00:00Z",
    })

total = sum(x["kg"] for x in rows)
lines = ["""-- ============================================================================
-- External biochar purchases, from the workbook's "External biochar" sheet.
--
-- Generated by scripts/gen-external-biochar.py — do not hand-edit; regenerate.
--
-- Bought-in biochar, not produced on site. Loaded as `warehouse` entries with
-- product "External Biochar" (that stage already carries exactly that option),
-- so no schema, stage or form changes are needed.
--
-- Volumes are normalized to kg. The sheet writes free text such as "3 Tonne";
-- the original wording is preserved in remarks so the conversion is auditable.
--
-- Batch ids are synthesized as EXT-<SOURCE>-<YYYYMMDD> because the sheet has no
-- id column. They identify a receipt that happened; they assert NO link to any
-- production batch or shipment.
--
-- ‼️  CARBON ACCOUNTING: this material was produced by a third party. It counts
--     as supply for physical mass balance, but must NOT be claimed as own
--     production for CORC issuance — whoever produced it has that claim.
--     massBalance.ts keeps the two separate; don't collapse them.
--
-- Safe to re-run: `on conflict (id) do nothing`.
-- ============================================================================

begin;
"""]
for doc in docs:
    lines.append(
        "insert into work_process_entries (id, data) values ('%s', '%s'::jsonb) "
        "on conflict (id) do nothing;"
        % (doc["Id"], json.dumps(doc).replace("'", "''"))
    )
lines.append(f"""
-- Sanity check: {len(docs)} row(s), {total:g} kg of external biochar.
select count(*) as external_rows,
       sum((data->'Values'->>'quantity')::numeric) as total_kg
from work_process_entries
where data->>'StageKey' = 'warehouse'
  and data->'Values'->>'product' = 'External Biochar';

commit;
""")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines))

print(f"rows: {len(docs)}  total: {total:g} kg  ->  {OUT}")
for d in docs:
    print(f"  {d['Values']['batch_id']:<32} {d['Values']['quantity']:>8} kg  {d['Values']['date']}")
if total != 3000:
    print(f"NOTE: Dashboard reports 3000 kg external biochar received; this run totals {total:g} kg.",
          file=sys.stderr)
